version: '3.8'
services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crypto_price_alert_development
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    command: bundle exec rails s -b '0.0.0.0' -p 3000
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/crypto_price_alert_development
      REDIS_URL: redis://redis:6379/1
      RAILS_ENV: development
      SECRET_KEY: W5X38gj93f0W

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - redis
      - db
    environment:
      REDIS_URL: redis://redis:6379/1
    volumes:
      - .:/app

volumes:
  postgres_data:
